name: build-and-push

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u user --password-stdin

      - name: Build
        run: docker build -t ragapp:latest .

      - name: Push
        run: docker push ragapp:latest